<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-TTL6LUL" ignored="0" name="InsertUser" tests="8" failures="1" timestamp="2021-02-26T19:38:18 ICT" time="0.77" errors="0">
  <testcase name="insertUser" time="0.092" classname="UnitTest.UserDAOTest"/>
  <testcase name="insertUser1" time="0.039" classname="UnitTest.UserDAOTest"/>
  <testcase name="insertUser2" time="0.035" classname="UnitTest.UserDAOTest"/>
  <testcase name="insertUser3" time="0.041" classname="UnitTest.UserDAOTest"/>
  <testcase name="insertUser4" time="0.034" classname="UnitTest.UserDAOTest"/>
  <testcase name="insertUser5" time="0.043" classname="UnitTest.UserDAOTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at UnitTest.UserDAOTest.insertUser5(UserDAOTest.java:124)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- insertUser5 -->
  <testcase name="insertUser6" time="0.044" classname="UnitTest.UserDAOTest"/>
  <testcase name="insertUser7" time="0.035" classname="UnitTest.UserDAOTest"/>
</testsuite> <!-- InsertUser -->
